In [823]:
import pandas as pd
import numpy as np
import unicodedata
import re
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:root@localhost:5433/db_docs')
df = pd.read_excel('eda_prueba.xlsx')

In [824]:
def eliminar_tildes(texto):
    if not isinstance(texto, str): return texto
    return "".join(c for c in unicodedata.normalize('NFD', texto) 
                   if unicodedata.category(c) != 'Mn')

def normalizar(texto):
    if not isinstance(texto, str): return texto
    
    texto = texto.upper()
    texto = eliminar_tildes(texto)
    texto = re.sub(r'\.\s*', '', texto) 
    texto = re.sub(r'\s+', ' ', texto).strip()
    
    return texto

In [825]:
meses = {
    'enero': 'January', 'febrero': 'February', 'marzo': 'March', 'abril': 'April',
    'mayo': 'May', 'amyo': 'May', 'junio': 'June', 'julio': 'July', 'agosto': 'August',
    'septiembre': 'September', 'octubre': 'October', 'octubte': 'October', 'noviembre': 'November', 'diciembre': 'December',
    '20211':'2021', '20201': '2021'
}

In [826]:
#mostrar errores en explode fechas|documentos
#errores = df_mem_pr_evp[df_mem_pr_evp['codigo_final'].str.len() != df_mem_pr_evp['fecha_documento'].str.len()]

#Mostramos las columnas problemáticas y sus longitudes para diagnosticar
#print(f"Filas con error: {len(errores)}")
#display(errores[['codigo_final', 'fecha_documento']])

In [827]:
df.rename(columns = {
    'PRESUNTO RESPONSABLE': 'proveedor_id',
    'CÉDULA - RUC': 'cedula_ruc',
    'Cantón': 'canton',
    'Ciudad': 'ciudad',
    'Provincia': 'provincia',
    'UNIDAD REQUIRIENTE': 'unidad_id',
    'SERVICIO CONTROLADO': 'servicio_id'
}, inplace = True)
df['proveedor_id'] = df['proveedor_id'].apply(normalizar)
df['servicio_id'] = df['servicio_id'].apply(normalizar)
df['servicio_id'] = df['servicio_id'].str.upper()
df['cedula_ruc'] = df['cedula_ruc'].astype(str)

In [828]:
df_proveedores = df.iloc[:, 1:6]
print(f"\nProveedores ({df_proveedores['proveedor_id'].nunique(dropna=True)} únicos):")
print(df_proveedores['proveedor_id'].value_counts(dropna=False))
print(f"\nCedula/Ruc ({df_proveedores['cedula_ruc'].nunique(dropna=True)} únicos):")
print(df_proveedores['cedula_ruc'].value_counts(dropna=False))
print(f"\nCantón ({df_proveedores['canton'].nunique(dropna=True)} únicos):")
print(df_proveedores['canton'].str.upper().value_counts(dropna=False))
print(f"\nCiudad ({df_proveedores['ciudad'].nunique(dropna=True)} únicos):")
print(df_proveedores['ciudad'].str.upper().value_counts(dropna=False))
print(f"\nProvincia ({df_proveedores['provincia'].nunique(dropna=True)} únicos):")
print(df_proveedores['provincia'].value_counts(dropna=False))

Proveedores (1249 únicos):
proveedor_id
CORPORACION NACIONAL DE TELECOMUNICACIONES CNT EP        126
CONSORCIO ECUATORIANO DE TELECOMUNICACIONES SACONECEL    100
OTECEL SA                                                 77
SERVICIOS DE TELECOMUNICACIONES SETEL SA                  54
ESMERALDAVISION SA                                        15
                                                        ...
BRAVO PALMA RAMON EDUARDO                                  1
CENTROS COMERCIALES DEL ECUADOR CA                         1
IZA GUALLASAMIN JUAN FRANCISCO                             1
CEBALLOS CLAROS FERLEY ANDRE                               1
CALDERON CEVALLOS EDWIN RENAN                              1
Name: count, Length: 1249, dtype: int64

Cedula/Ruc (1127 únicos):
cedula_ruc
NaN               194
1768152560001     127
1791251237001     101
1791256115001      77
1791847652001      53
                 ...
0-301165668001      1
1091783351001       1
1301923205001       1
1790009378001       1
1713846937001       1
Name: count, Length: 1128, dtype: int64

Cantón (154 únicos):
canton
QUITO             1783
IBARRA             157
ESMERALDAS         113
NaN                103
OTAVALO             84
                  ...
PABLO SEXTO          1
SANTO DOMINGO        1
RIO VERDE            1
PORTOVIEJO           1
CATAMAYO             1
Name: count, Length: 152, dtype: int64

Ciudad (175 únicos):
ciudad
QUITO                        1757
IBARRA                        164
ESMERALDAS                    116
OTAVALO                        84
NaN                            73
                             ...
FRANCISCO DE ORELLANA           1
COTACACHI                       1
LA JOYA DE LOS TSACHILAS        1
PORTOVIEJO                      1
CATAMAYO                        1
Name: count, Length: 173, dtype: int64

Provincia (23 únicos):
provincia
PICHINCHA                         2014
IMBABURA                           348
ESMERALDAS                         222
SUCUMBÍOS                          146
NaN                                 94
ORELLANA                            90
CARCHI                              79
NAPO                                60
GUAYAS                              39
AZUAY                               18
MANABÍ                              15
SANTO DOMINGO DE LOS TSÁCHILAS       9
CHIMBORAZO                           9
LOJA                                 8
CAÑAR                                7
LOS RÍOS                             6
SANTA ELENA                          4
TUNGURAHUA                           4
MORONA SANTIAGO                      3
ZAMORA CHINCHIPE                     2
PASTAZA                              2
COTOPAXI                             2
EL ORO                               1
GALÁPAGOS                            1
Name: count, dtype: int64

In [829]:
df_proveedores.drop_duplicates(keep = 'last', inplace = True)
df_proveedores.rename(columns = {'proveedor_id': 'nombre'}, inplace=True)

In [830]:
df_proveedores.to_sql('proveedor', con=engine, if_exists = 'append', index = False)

618

In [831]:
df_unidades = df.iloc[:, 6]
print(f"\nUNIDADES ({df_unidades.nunique(dropna=True)} únicos):")
print(df_unidades.value_counts(dropna=False))

UNIDADES (19 únicos):
unidad_id
CCON                     1147
CZO2                      746
CTDG                      606
CCDS                      322
CCDE                      152
CTDE                      103
CTHB                       41
DCS                        31
CTDS                       13
CTC                         6
DCE                         4
DCI                         3
NaN                         2
DIS                         1
DEFENSORIA DEL PUEBLO       1
DIE                         1
CZO4                        1
CZO3                        1
CAFI                        1
QUITO                       1
Name: count, dtype: int64

In [832]:
df_unidades.drop_duplicates(keep = 'last', inplace = True)
df_unidades.fillna('N/A', inplace = True)
df_unidades.rename('codigo', inplace=True)

50                        DCE
66                        DCI
74                        DIS
77                        CTC
87      DEFENSORIA DEL PUEBLO
100                       DIE
122                       DCS
448                      CZO4
1224                     CZO3
2252                     CAFI
2298                      N/A
3023                     CTHB
3040                     CCDE
3070                     CCON
3138                     CZO2
3164                    QUITO
3170                     CTDS
3174                     CCDS
3175                     CTDE
3182                     CTDG
Name: codigo, dtype: str

In [833]:
df_unidades.to_sql('unidad', con=engine, if_exists = 'append', index = False)

20

In [834]:
df_servicios = df.iloc[:, 8]
print(f"\nServicios ({df_servicios.nunique(dropna=True)} únicos):")
print(df_servicios.value_counts(dropna=False))

Servicios (39 únicos):
servicio_id
SAI                                                   1159
RED PRIVADA                                            379
RTV                                                    246
RADIODIFUSION FM                                       220
SRC                                                    206
SMA                                                    199
AVS                                                    185
SVA                                                    144
COMUNAL                                                120
STF                                                    101
TV                                                      65
TELECOMUNICACIONES MOVILES POR SATELITE                 27
RADIODIFUSION AM                                        24
SPT                                                     15
SERVICIO DE SEGMENTO ESPACIAL                           13
PRP                                                     13
HOMOLOGACION                                            10
SAI- SPT                                                 7
FMT                                                      6
PROVEEDOR DE INFRAESTRUCTURA                             5
EC                                                       5
SC                                                       5
TRANSPORTE INTERNACIONAL MODALIDAD CABLE SUBMARINO       4
RADIODIFUSION SONORA                                     3
RP                                                       3
SMA - OMV                                                2
O&S                                                      2
ACREDITACION                                             2
TEL                                                      2
TIWS                                                     1
BYPASS                                                   1
IPTV                                                     1
TDT                                                      1
NO AUTORIZADO                                            1
VARIOS                                                   1
NaN                                                      1
SP                                                       1
PRR                                                      1
COMUNALES                                                1
AVS/SAI                                                  1
Name: count, dtype: int64

In [835]:
df_servicios.drop_duplicates(keep = 'last', inplace = True)
df_servicios.fillna('N/A', inplace = True)
df_servicios.rename('servicio', inplace = True)

67                                                   TIWS
416     TRANSPORTE INTERNACIONAL MODALIDAD CABLE SUBMA...
491                          PROVEEDOR DE INFRAESTRUCTURA
583                                                BYPASS
779                                                  IPTV
1093                                                  TDT
1133                                            SMA - OMV
1277                                        NO AUTORIZADO
1288                                                  FMT
2148                                         HOMOLOGACION
2193                                             SAI- SPT
2253              TELECOMUNICACIONES MOVILES POR SATELITE
2413                                                  O&S
2508                                               VARIOS
2509                                                   EC
2512                                         ACREDITACION
2673                                                  N/A
2773                                                  SPT
2895                                                  SRC
2946                                                   TV
3022                        SERVICIO DE SEGMENTO ESPACIAL
3051                                              COMUNAL
3080                                                  SMA
3110                                                   SP
3113                                                  TEL
3115                                                  PRR
3117                                     RADIODIFUSION AM
3122                                            COMUNALES
3123                                          RED PRIVADA
3129                                                  STF
3140                                              AVS/SAI
3143                                 RADIODIFUSION SONORA
3151                                                  AVS
3155                                                  SVA
3169                                                   RP
3175                                                  RTV
3178                                                  PRP
3179                                                   SC
3181                                     RADIODIFUSION FM
3182                                                  SAI
Name: servicio, dtype: str

In [836]:
df_servicios.to_sql('servicio', con=engine, if_exists = 'append', index = False)

40

In [837]:
df_proveedor_db = pd.read_sql('select id, nombre as proveedor_id, cedula_ruc, canton, ciudad, provincia from proveedor', engine)
df_unidad_db = pd.read_sql('select id, codigo as unidad_id from unidad', engine)
df_servicio_db = pd.read_sql('select id, servicio as servicio_id from servicio', engine)

In [838]:
df_tramites = df.iloc[:, np.r_[1:6, 6, 8, 10, 16, 52, 123]]
df_tramites['fecha_insercion'] = pd.to_datetime('now')
df_tramites.rename(columns = {
    'ASUNTO / EXTRACTO HECHO DETECTADO': 'asunto',
    'PROCEDE INICIO DE PAS (SI /NO)': 'prosigue',
    'ESTADO GENERAL': 'estado',
}, inplace = True)
df_tramites['unidad_id'] = df_tramites['unidad_id'].fillna('N/A')
df_tramites['servicio_id'] = df_tramites['servicio_id'].fillna('N/A')

df_tramites = df_tramites.merge(df_proveedor_db, on=['proveedor_id', 'cedula_ruc', 'canton', 'ciudad', 'provincia'], how='left')
df_tramites = df_tramites.merge(df_unidad_db, on='unidad_id', how='left')
df_tramites = df_tramites.merge(df_servicio_db, on='servicio_id', how='left')

df_tramites['proveedor_id'] = df_tramites['id_x']
df_tramites['unidad_id'] = df_tramites['id_y']
df_tramites['servicio_id'] = df_tramites['id']

MAP_PROSIGUE = {'SI': True, 'NO': False, None: True}
df_tramites['prosigue'] = df_tramites['prosigue'].map(MAP_PROSIGUE)

df_tramites.drop_duplicates(subset = 'MEMORANDO  PETICION INICIO PAS ', keep = 'first', inplace = True)
df_tramites.index.rename('id', inplace = True)
df_tramites.index = df_tramites.index +1

In [839]:
df_tramites[['proveedor_id',
                  'unidad_id',
                  'servicio_id',
                  'fecha_insercion',
                  'asunto',
                  'prosigue',
                  'estado']].to_sql('tramite', con = engine, if_exists = 'append')

121

In [840]:
df_documentos = df.iloc[:, 10:121]
df_documentos.rename(columns = {'MEMORANDO  PETICION INICIO PAS ': 'tramite_id'}, inplace = True)
df_documentos['CODIGO_MEMORANDO'] = df_documentos['tramite_id']

In [841]:
#
#
# INSERCION DE DOCUMENTOS
#
#

In [842]:
df_tramites_db = pd.read_sql('select * from v_jp', engine)

In [843]:
df_memosPAS = df.iloc[:, np.r_[0,1,6,8,10,11,16]]
df_memosPAS.rename(columns = {
    'No': 'tramite_id',
    'ASUNTO / EXTRACTO HECHO DETECTADO': 'asunto',
    'MEMORANDO  PETICION INICIO PAS ': 'codigo_final',
    'FECHA MEMORANDO  PETICION INICIO PAS ': 'fecha_documento'
}, inplace = True)
df_memosPAS['tipo_documento_id'] = 1
df_memosPAS['es_manual'] = True
df_memosPAS['archivado'] = False

df_memosPAS.drop_duplicates(subset='codigo_final', keep = 'first', inplace = True)
df_memosPAS.drop(columns=['proveedor_id','unidad_id','servicio_id','asunto'], inplace = True)

In [844]:
df_memosPAS.to_sql('documento', con = engine, if_exists='append', index = False)

121

In [845]:
df_documentos.rename(columns = {'tramite_id': 'codigo_memo'}, inplace = True)
df_memos_db = pd.read_sql('select tramite_id, codigo_final as codigo_memo, id as id_memo from documento where tipo_documento_id = 1', engine)

In [846]:
df_peticiones = df_documentos.iloc[:, np.r_[0,2,3]]
df_peticiones = df_peticiones.replace(['-','No hay petición razonada'],None)
df_peticiones = df_peticiones.merge(df_memos_db, on='codigo_memo', how='left')
df_peticiones.rename(columns = {
    'PETICIÓN RAZONADA': 'codigo_final',
    'FECHA PETICIÓN RAZONADA': 'fecha_documento'
}, inplace = True)
df_peticiones['tipo_documento_id'] = 2
df_peticiones['es_manual'] = True
df_peticiones['archivado'] = False
df_peticiones.dropna(subset = ['codigo_final'], inplace = True)
df_peticiones.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_peticiones.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [847]:
df_peticiones.to_sql('documento', con = engine, if_exists='append', index = False)

104

In [848]:
df_firstinf = df_documentos.iloc[:, np.r_[0,4,5]]
df_firstinf = df_firstinf.merge(df_memos_db, on='codigo_memo', how='left')
df_firstinf.rename(columns = {
    'INFORME TÉCNICO': 'codigo_final',
    'FECHA INFORME TÉCNICO': 'fecha_documento'
}, inplace = True)
df_firstinf['tipo_documento_id'] = 15
df_firstinf['es_manual'] = True
df_firstinf['archivado'] = False
df_firstinf.dropna(subset = ['codigo_final'], inplace = True)
df_firstinf.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_firstinf.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [849]:
df_firstinf.to_sql('documento', con = engine, if_exists='append', index = False)

970

In [850]:
df_actuacionp = df_documentos.iloc[:, np.r_[0,8,9]]
df_actuacionp = df_actuacionp.merge(df_memos_db, on='codigo_memo', how='left')
df_actuacionp.rename(columns = {
    'No. ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_actuacionp['tipo_documento_id'] = 4
df_actuacionp['es_manual'] = True
df_actuacionp['archivado'] = False
df_actuacionp['documento_origen_id'] = df_actuacionp['id_memo']
df_actuacionp.dropna(subset = ['codigo_final'], inplace = True)
df_actuacionp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_actuacionp.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [851]:
df_actuacionp.to_sql('documento', con = engine, if_exists='append', index = False)

278

In [852]:
df_ap_db = pd.read_sql('select id, codigo_final as codigo_ap from documento where tipo_documento_id = 4', engine)

In [853]:
df_oficio_ap = df_documentos.iloc[:, np.r_[0,8,10,11]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_oficio_ap = df_oficio_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_oficio_ap = df_oficio_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_oficio_ap.rename(columns = {
    'OFICIO NOTIFICACIÓN ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA OFICIO NOTIFICACIÓN ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_oficio_ap['tipo_documento_id'] = 12
df_oficio_ap['subtipo_documento_id'] = 13
df_oficio_ap['es_manual'] = True
df_oficio_ap['archivado'] = False
df_oficio_ap['documento_origen_id'] = df_oficio_ap['id']
df_oficio_ap.dropna(subset = ['codigo_final'], inplace = True)
df_oficio_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_oficio_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_ap', 'id'], inplace = True)

df_oficio_ap['fecha_documento'] = df_oficio_ap['fecha_documento'].str.lower().str.replace(' de ', ' ')

df_oficio_ap['codigo_final'] = df_oficio_ap['codigo_final'].str.split('\n')
df_oficio_ap['fecha_documento'] = df_oficio_ap['fecha_documento'].str.split('\n')

df_oficio_ap = df_oficio_ap.explode(['codigo_final', 'fecha_documento'])

df_oficio_ap['codigo_final'] = df_oficio_ap['codigo_final'].str.strip()
df_oficio_ap['fecha_documento'] = df_oficio_ap['fecha_documento'].str.strip()

for esp, ing in meses.items():
    df_oficio_ap['fecha_documento'] = df_oficio_ap['fecha_documento'].str.replace(esp, ing)
    
df_oficio_ap['fecha_documento'] = df_oficio_ap['fecha_documento'].str.strip()
df_oficio_ap['fecha_documento'] = pd.to_datetime(df_oficio_ap['fecha_documento'], format='mixed')

In [854]:
df_oficio_ap.to_sql('documento', con = engine, if_exists='append', index = False)

96

In [855]:
df_memo_ap = df_documentos.iloc[:, np.r_[0,8,12,13]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_memo_ap = df_memo_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_memo_ap = df_memo_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_memo_ap.rename(columns = {
    'MEMORANDO NOTIFICACION ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA MEMORANDO NOTIFICACION ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_memo_ap['tipo_documento_id'] = 13
df_memo_ap['subtipo_documento_id'] = 14
df_memo_ap['es_manual'] = True
df_memo_ap['archivado'] = False
df_memo_ap['documento_origen_id'] = df_memo_ap['id']
df_memo_ap.dropna(subset = ['codigo_final'], inplace = True)
df_memo_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_memo_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_ap', 'id'], inplace = True)

df_memo_ap['fecha_documento'] = df_memo_ap['fecha_documento'].str.lower().str.replace(' de ', ' ')
for esp, ing in meses.items():
    df_memo_ap['fecha_documento'] = df_memo_ap['fecha_documento'].str.replace(esp, ing)
    
df_memo_ap['fecha_documento'] = df_memo_ap['fecha_documento'].str.strip()
df_memo_ap['fecha_documento'] = pd.to_datetime(df_memo_ap['fecha_documento'], format='mixed')

In [856]:
df_memo_ap.to_sql('documento', con = engine, if_exists='append', index = False)

90

In [857]:
df_pr_ap = df_documentos.iloc[:, np.r_[0,8,15,16]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_pr_ap = df_pr_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_pr_ap = df_pr_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_pr_ap.rename(columns = {
    'PROVIDENCIAS ACTUACIONES PREVIAS': 'codigo_final',
    'FECHA PROVIDENCIAS ACTUACIONES PREVIAS': 'fecha_documento'
}, inplace = True)
df_pr_ap['tipo_documento_id'] = 7
df_pr_ap['subtipo_documento_id'] = 3
df_pr_ap['es_manual'] = True
df_pr_ap['archivado'] = False
df_pr_ap['documento_origen_id'] = df_pr_ap['id']
df_pr_ap.dropna(subset = ['codigo_final'], inplace = True)
df_pr_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_pr_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_ap', 'id'], inplace = True)

df_pr_ap['codigo_final'] = df_pr_ap['codigo_final'].str.split('\n')
df_pr_ap['fecha_documento'] = df_pr_ap['fecha_documento'].str.split('\n')

df_pr_ap = df_pr_ap.explode(['codigo_final', 'fecha_documento'])

df_pr_ap['codigo_final'] = df_pr_ap['codigo_final'].str.strip()
df_pr_ap['fecha_documento'] = df_pr_ap['fecha_documento'].str.strip()

df_pr_ap['fecha_documento'] = df_pr_ap['fecha_documento'].str.lower().str.replace(' de ', ' ')
for esp, ing in meses.items():
    df_pr_ap['fecha_documento'] = df_pr_ap['fecha_documento'].str.replace(esp, ing)
    
df_pr_ap['fecha_documento'] = df_pr_ap['fecha_documento'].replace(['arcotel-czo2-pr-2022-069'], None)
df_pr_ap['fecha_documento'] = pd.to_datetime(df_pr_ap['fecha_documento'], format='mixed')

In [858]:
df_pr_ap.to_sql('documento', con = engine, if_exists='append', index = False)

33

In [859]:
df_pr_ap_db = pd.read_sql('select id, codigo_final as codigo_pr_ap from documento where tipo_documento_id = 7 and subtipo_documento_id = 3', engine)

In [860]:
df_oficio_pr_ap = df_documentos.iloc[:, np.r_[0,15,17,18]].rename(columns={'PROVIDENCIAS ACTUACIONES PREVIAS':'codigo_pr_ap'})
df_oficio_pr_ap = df_oficio_pr_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_oficio_pr_ap = df_oficio_pr_ap.merge(df_pr_ap_db, on='codigo_pr_ap', how='left')
df_oficio_pr_ap.rename(columns = {
    'OFICIO ENVIO PROVIDENCIAS ACTUACIONES PREVIAS': 'codigo_final',
    'FECHA ENVIO OFICIO PROVIDENCIAS ACTUACIONES PREVIAS': 'fecha_documento'
}, inplace = True)
df_oficio_pr_ap['tipo_documento_id'] = 12
df_oficio_pr_ap['subtipo_documento_id'] = 13
df_oficio_pr_ap['es_manual'] = True
df_oficio_pr_ap['archivado'] = False
df_oficio_pr_ap['documento_origen_id'] = df_oficio_pr_ap['id']
df_oficio_pr_ap.dropna(subset = ['codigo_final'], inplace = True)
df_oficio_pr_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_oficio_pr_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_pr_ap', 'id'], inplace = True)

df_oficio_pr_ap['codigo_final'] = df_oficio_pr_ap['codigo_final'].str.split('\n')
df_oficio_pr_ap['fecha_documento'] = df_oficio_pr_ap['fecha_documento'].str.split('\n')

df_oficio_pr_ap = df_oficio_pr_ap.explode(['codigo_final', 'fecha_documento'])

df_oficio_pr_ap['codigo_final'] = df_oficio_pr_ap['codigo_final'].str.strip()
df_oficio_pr_ap['fecha_documento'] = df_oficio_pr_ap['fecha_documento'].str.strip()

df_oficio_pr_ap['fecha_documento'] = df_oficio_pr_ap['fecha_documento'].str.lower().str.replace(' de ', ' ')
for esp, ing in meses.items():
    df_oficio_pr_ap['fecha_documento'] = df_oficio_pr_ap['fecha_documento'].str.replace(esp, ing)
df_oficio_pr_ap['fecha_documento'] = pd.to_datetime(df_oficio_pr_ap['fecha_documento'], format='mixed')

#Correccion de Algunos documentos

df_oficio_pr_ap.loc[df_oficio_pr_ap['tramite_id'] == 552, 'documento_origen_id'] = 8384
df_oficio_pr_ap.loc[df_oficio_pr_ap['tramite_id'] == 723, 'documento_origen_id'] = 8390
df_oficio_pr_ap.loc[df_oficio_pr_ap['tramite_id'] == 1007, 'documento_origen_id'] = 8394

In [861]:
df_oficio_pr_ap.to_sql('documento', con = engine, if_exists='append', index = False)

32

In [862]:
df_memo_pr_ap = df_documentos.iloc[:, np.r_[0,15,19,20]].rename(columns={'PROVIDENCIAS ACTUACIONES PREVIAS':'codigo_pr_ap'})
df_memo_pr_ap = df_memo_pr_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_memo_pr_ap = df_memo_pr_ap.merge(df_pr_ap_db, on='codigo_pr_ap', how='left')
df_memo_pr_ap.rename(columns = {
    'PRUEBA DE NOTIFICACIÓN PROVIDENCIAS ACTUACIONES PREVIAS': 'codigo_final',
    'FECHA PRUEBA DE NOTIFICACIÓN PROVIDENCIAS ACTUACIONES PREVIAS': 'fecha_documento'
}, inplace = True)
df_memo_pr_ap['tipo_documento_id'] = 13
df_memo_pr_ap['subtipo_documento_id'] = 15
df_memo_pr_ap['es_manual'] = True
df_memo_pr_ap['archivado'] = False
df_memo_pr_ap['documento_origen_id'] = df_memo_pr_ap['id']
df_memo_pr_ap.dropna(subset = ['codigo_final'], inplace = True)
df_memo_pr_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_memo_pr_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_pr_ap', 'id'], inplace = True)

df_memo_pr_ap['codigo_final'] = df_memo_pr_ap['codigo_final'].str.split('\n')
df_memo_pr_ap['fecha_documento'] = df_memo_pr_ap['fecha_documento'].str.split('\n')

df_memo_pr_ap = df_memo_pr_ap.explode(['codigo_final', 'fecha_documento'])

df_memo_pr_ap['codigo_final'] = df_memo_pr_ap['codigo_final'].str.strip()
df_memo_pr_ap['fecha_documento'] = df_memo_pr_ap['fecha_documento'].str.strip()

df_memo_pr_ap['fecha_documento'] = df_memo_pr_ap['fecha_documento'].str.lower().str.replace(' de ', ' ')
for esp, ing in meses.items():
    df_memo_pr_ap['fecha_documento'] = df_memo_pr_ap['fecha_documento'].str.replace(esp, ing)
df_memo_pr_ap['fecha_documento'] = pd.to_datetime(df_memo_pr_ap['fecha_documento'], format='mixed')

#Correccion de Algunos documentos

df_memo_pr_ap.loc[df_memo_pr_ap['tramite_id'] == 552, 'documento_origen_id'] = 8384
df_memo_pr_ap.loc[df_memo_pr_ap['tramite_id'] == 723, 'documento_origen_id'] = 8390
df_memo_pr_ap.loc[df_memo_pr_ap['tramite_id'] == 1007, 'documento_origen_id'] = 8394

In [863]:
df_memo_pr_ap.to_sql('documento', con = engine, if_exists='append', index = False)

30

In [864]:
df_memo_of_ap = df_documentos.iloc[:, np.r_[0, 8,21,22]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_memo_of_ap = df_memo_of_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_memo_of_ap = df_memo_of_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_memo_of_ap.rename(columns = {
    'MEMORANDOS - OFICIOS - ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA MEMORANDOS - OFICIOS - ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_memo_of_ap['tipo_documento_id'] = 13
df_memo_of_ap['subtipo_documento_id'] = 23
df_memo_of_ap['es_manual'] = True
df_memo_of_ap['archivado'] = False
df_memo_of_ap['documento_origen_id'] = df_memo_of_ap['id']
df_memo_of_ap.dropna(subset = ['codigo_final'], inplace = True)
df_memo_of_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_memo_of_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_ap', 'id'], inplace = True)

df_memo_of_ap['codigo_final'] = df_memo_of_ap['codigo_final'].str.split('\n')
df_memo_of_ap['fecha_documento'] = df_memo_of_ap['fecha_documento'].str.split('\n')

#Correccion
df_memo_of_ap.at[360, 'fecha_documento'].pop(0)
df_memo_of_ap.at[615, 'fecha_documento'] = ['']
df_memo_of_ap.at[1053, 'codigo_final'].pop(1)

df_memo_of_ap = df_memo_of_ap.explode(['codigo_final', 'fecha_documento'])

df_memo_of_ap['codigo_final'] = df_memo_of_ap['codigo_final'].str.strip()
df_memo_of_ap['fecha_documento'] = df_memo_of_ap['fecha_documento'].str.strip()

df_memo_of_ap['fecha_documento'] = df_memo_of_ap['fecha_documento'].str.lower().str.replace(' de ', '')
df_memo_of_ap['fecha_documento'] = df_memo_of_ap['fecha_documento'].str.lower().str.replace(' del ', '')
for esp, ing in meses.items():
    df_memo_of_ap['fecha_documento'] = df_memo_of_ap['fecha_documento'].str.replace(esp, ing)
df_memo_of_ap['fecha_documento'] = pd.to_datetime(df_memo_of_ap['fecha_documento'], format='mixed')

In [865]:
df_memo_of_ap.to_sql('documento', con = engine, if_exists='append', index = False)

152

In [866]:
df_r_memo_of_ap = df_documentos.iloc[:, np.r_[0, 8,23,24]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_r_memo_of_ap = df_r_memo_of_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_r_memo_of_ap = df_r_memo_of_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_r_memo_of_ap.rename(columns = {
    'RESPUESTA MEMORANDOS - OFICIOS -  ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA - RESPUESTA MEMORANDOS - OFICIOS -  ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_r_memo_of_ap['tipo_documento_id'] = 13
df_r_memo_of_ap['subtipo_documento_id'] = 24
df_r_memo_of_ap['es_manual'] = True
df_r_memo_of_ap['archivado'] = False
df_r_memo_of_ap['documento_origen_id'] = df_r_memo_of_ap['id']
df_r_memo_of_ap.dropna(subset = ['codigo_final'], inplace = True)
df_r_memo_of_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_r_memo_of_ap.drop(columns=['codigo_memo', 'id_memo','codigo_ap', 'id'], inplace = True)

df_r_memo_of_ap['codigo_final'] = df_r_memo_of_ap['codigo_final'].str.replace('/', '\n')

df_r_memo_of_ap['fecha_documento'] = df_r_memo_of_ap['fecha_documento'].str.lower().str.replace(' de ', ' ')
df_r_memo_of_ap['fecha_documento'] = df_r_memo_of_ap['fecha_documento'].str.lower().str.replace('/', '\n')

df_r_memo_of_ap['codigo_final'] = df_r_memo_of_ap['codigo_final'].str.split('\n')
df_r_memo_of_ap['fecha_documento'] = df_r_memo_of_ap['fecha_documento'].str.split('\n')

#Correccion
df_r_memo_of_ap.at[421, 'codigo_final'].pop(0)
df_r_memo_of_ap.at[466, 'codigo_final'].pop(0)
df_r_memo_of_ap.at[615, 'fecha_documento'] = ['']
df_r_memo_of_ap.at[814, 'codigo_final'].pop(0)
df_r_memo_of_ap.at[849, 'fecha_documento'].pop(0)
df_r_memo_of_ap.at[889, 'codigo_final'].pop(0)
df_r_memo_of_ap.at[889, 'codigo_final'].pop(1)
df_r_memo_of_ap.at[889, 'codigo_final'].pop(2)
df_r_memo_of_ap.at[1086, 'fecha_documento'].pop(0)

df_r_memo_of_ap = df_r_memo_of_ap.explode(['codigo_final', 'fecha_documento'])

df_r_memo_of_ap['codigo_final'] = df_r_memo_of_ap['codigo_final'].str.strip()
df_r_memo_of_ap['fecha_documento'] = df_r_memo_of_ap['fecha_documento'].str.strip()

for esp, ing in meses.items():
    df_r_memo_of_ap['fecha_documento'] = df_r_memo_of_ap['fecha_documento'].str.replace(esp, ing)
df_r_memo_of_ap['fecha_documento'] = pd.to_datetime(df_r_memo_of_ap['fecha_documento'], format='mixed')

df_r_memo_of_ap.dropna(subset = ['codigo_final'], inplace = True)
df_r_memo_of_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_r_memo_of_ap

,codigo_final,fecha_documento,tramite_id,tipo_documento_id,subtipo_documento_id,es_manual,archivado,documento_origen_id
164,ARCOTEL-CTRP-2022-0749-M,2022-03-17,165,13,24,True,False,8196.0
164,,NaT,165,13,24,True,False,8196.0
199,ARCOTEL-CZO2-2021-2195-M,2021-12-16,200,13,24,True,False,8201.0
200,ARCOTEL-CZO2-2021-2181-M,2021-12-13,201,13,24,True,False,8202.0
211,ARCOTEL-CZO2-2021-2159-M,2021-12-08,212,13,24,True,False,8204.0
...,...,...,...,...,...,...,...,...
1077,ARCOTEL-DEDA-2022-0596-M,2022-03-03,1078,13,24,True,False,8350.0
1077,ARCOTEL-DEDA-2022-0626-M,2022-03-07,1078,13,24,True,False,8350.0
1077,ARCOTEL-CCDS-2022-0072-M,2022-04-11,1078,13,24,True,False,8350.0
1086,ARCOTEL-CTRP-2022-0879-M,2022-03-25,1087,13,24,True,False,8351.0
1086,ARCOTEL-CZO2-2022-0671-M,2022-04-28,1087,13,24,True,False,8351.0

In [867]:
df_r_memo_of_ap.to_sql('documento', con = engine, if_exists='append', index = False)

141

In [868]:
df_i_ap = df_documentos.iloc[:, np.r_[0, 8,27,28]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_i_ap = df_i_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_i_ap = df_i_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_i_ap.rename(columns = {
    'INFORME DE ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA INFORME DE ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_i_ap['tipo_documento_id'] = 5
df_i_ap['subtipo_documento_id'] = 1
df_i_ap['es_manual'] = True
df_i_ap['archivado'] = False
df_i_ap['documento_origen_id'] = df_i_ap['id']
df_i_ap.dropna(subset = ['codigo_final'], inplace = True)
df_i_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_i_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_ap', 'id'], inplace = True)

In [869]:
df_i_ap.to_sql('documento', con = engine, if_exists='append', index = False)

257

In [870]:
df_i_ap_db = pd.read_sql('select id, codigo_final as codigo_i_ap from documento where tipo_documento_id = 5 and subtipo_documento_id = 1', engine)

In [871]:
df_of_i_ap = df_documentos.iloc[:, np.r_[0, 27,29,30]].rename(columns={'INFORME DE ACTUACIÓN PREVIA':'codigo_i_ap'})
df_of_i_ap = df_of_i_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_of_i_ap = df_of_i_ap.merge(df_i_ap_db, on='codigo_i_ap', how='left')
df_of_i_ap.rename(columns = {
    'OFICIO NOTIFICACIÓN INFORME DE ACTUACÓN PREVIA': 'codigo_final',
    'FECHA OFICIO NOTIFICACIÓN INFORME DE ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_of_i_ap['tipo_documento_id'] = 12
df_of_i_ap['subtipo_documento_id'] = 13
df_of_i_ap['es_manual'] = True
df_of_i_ap['archivado'] = False
df_of_i_ap['documento_origen_id'] = df_of_i_ap['id']
df_of_i_ap.dropna(subset = ['codigo_final'], inplace = True)
df_of_i_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_of_i_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_i_ap', 'id'], inplace = True)

In [872]:
df_of_i_ap.to_sql('documento', con = engine, if_exists='append', index = False)

84

In [873]:
df_mem_i_ap = df_documentos.iloc[:, np.r_[0, 27,31,32]].rename(columns={'INFORME DE ACTUACIÓN PREVIA':'codigo_i_ap'})
df_mem_i_ap = df_mem_i_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_i_ap = df_mem_i_ap.merge(df_i_ap_db, on='codigo_i_ap', how='left')
df_mem_i_ap.rename(columns = {
    'PRUEBA DE NOTIFICACIÓN DE INFORME DE ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA DE PRUEBA DE NOTIFICACIÓN DE INFORME DE ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_mem_i_ap['tipo_documento_id'] = 13
df_mem_i_ap['subtipo_documento_id'] = 15
df_mem_i_ap['es_manual'] = True
df_mem_i_ap['archivado'] = False
df_mem_i_ap['documento_origen_id'] = df_mem_i_ap['id']
df_mem_i_ap.dropna(subset = ['codigo_final'], inplace = True)
df_mem_i_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_i_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_i_ap', 'id'], inplace = True)

In [874]:
df_mem_i_ap.to_sql('documento', con = engine, if_exists='append', index = False)

84

In [875]:
df_r_i_ap = df_documentos.iloc[:, np.r_[0, 27,34,35]].rename(columns={'INFORME DE ACTUACIÓN PREVIA':'codigo_i_ap'})
df_r_i_ap = df_r_i_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_r_i_ap = df_r_i_ap.merge(df_i_ap_db, on='codigo_i_ap', how='left')
df_r_i_ap.rename(columns = {
    'RESPUESTA DE INFORME DE ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA - RESPUESTA DE INFORME DE ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_r_i_ap['tipo_documento_id'] = 14
df_r_i_ap['subtipo_documento_id'] = 28
df_r_i_ap['es_manual'] = True
df_r_i_ap['archivado'] = False
df_r_i_ap['documento_origen_id'] = df_r_i_ap['id']
df_r_i_ap.dropna(subset = ['codigo_final'], inplace = True)
df_r_i_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_r_i_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_i_ap', 'id'], inplace = True)

In [876]:
df_r_i_ap.to_sql('documento', con = engine, if_exists='append', index = False)

54

In [877]:
df_iF_ap = df_documentos.iloc[:, np.r_[0, 8,36,37]].rename(columns={'No. ACTUACIÓN PREVIA':'codigo_ap'})
df_iF_ap = df_iF_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_iF_ap = df_iF_ap.merge(df_ap_db, on='codigo_ap', how='left')
df_iF_ap.rename(columns = {
    'INFORME FINAL ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA INFORME FINAL ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_iF_ap['tipo_documento_id'] = 5
df_iF_ap['subtipo_documento_id'] = 2
df_iF_ap['es_manual'] = True
df_iF_ap['archivado'] = False
df_iF_ap['documento_origen_id'] = df_iF_ap['id']
df_iF_ap.dropna(subset = ['codigo_final'], inplace = True)
df_iF_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_iF_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_ap', 'id'], inplace = True)

In [878]:
df_iF_ap.to_sql('documento', con = engine, if_exists='append', index = False)

245

In [879]:
df_iF_ap_db = pd.read_sql('select id, codigo_final as codigo_iF_ap from documento where tipo_documento_id = 5 and subtipo_documento_id = 2', engine)

In [880]:
df_of_iF_ap = df_documentos.iloc[:, np.r_[0, 36,38,39]].rename(columns={'INFORME FINAL ACTUACIÓN PREVIA':'codigo_if_ap'})
df_of_iF_ap = df_of_iF_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_of_iF_ap = df_of_iF_ap.merge(df_iF_ap_db, on='codigo_if_ap', how='left')
df_of_iF_ap.rename(columns = {
    'OFICIO DE NOTIFICACIÓN INFORME FINAL ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA - DE OFICIO DE NOTIFICACIÓN INFORME FINAL ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_of_iF_ap['tipo_documento_id'] = 12
df_of_iF_ap['subtipo_documento_id'] = 13
df_of_iF_ap['es_manual'] = True
df_of_iF_ap['archivado'] = False
df_of_iF_ap['documento_origen_id'] = df_of_iF_ap['id']
df_of_iF_ap.dropna(subset = ['codigo_final'], inplace = True)
df_of_iF_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_of_iF_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_if_ap', 'id'], inplace = True)

In [881]:
df_of_iF_ap.to_sql('documento', con = engine, if_exists='append', index = False)

81

In [882]:
df_mem_if_ap = df_documentos.iloc[:, np.r_[0, 36,40,41]].rename(columns={'INFORME FINAL ACTUACIÓN PREVIA':'codigo_if_ap'})
df_mem_if_ap = df_mem_if_ap.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_if_ap = df_mem_if_ap.merge(df_iF_ap_db, on='codigo_if_ap', how='left')
df_mem_if_ap.rename(columns = {
    'MEMORANDO DE NOTIFICACIÓN DE INFORME FINAL DE ACTUACIÓN PREVIA': 'codigo_final',
    'FECHA DE MEMORANDO DE NOTIFICACIÓN DE INFORME FINAL DE ACTUACIÓN PREVIA': 'fecha_documento'
}, inplace = True)
df_mem_if_ap['tipo_documento_id'] = 13
df_mem_if_ap['subtipo_documento_id'] = 14
df_mem_if_ap['es_manual'] = True
df_mem_if_ap['archivado'] = False
df_mem_if_ap['documento_origen_id'] = df_mem_if_ap['id']
df_mem_if_ap.dropna(subset = ['codigo_final'], inplace = True)
df_mem_if_ap.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_if_ap.drop(columns=['codigo_memo', 'id_memo', 'codigo_if_ap', 'id'], inplace = True)

In [883]:
df_mem_if_ap.to_sql('documento', con = engine, if_exists='append', index = False)

79

In [884]:
df_ijuridico = df_documentos.iloc[:, np.r_[0,43,44]]
df_ijuridico = df_ijuridico.merge(df_memos_db, on='codigo_memo', how='left')
df_ijuridico.rename(columns = {
    'INFORME JURIDICO PAS': 'codigo_final',
    'FECHA INFORME JURIDICO PAS': 'fecha_documento'
}, inplace = True)
df_ijuridico['tipo_documento_id'] = 11
df_ijuridico['es_manual'] = True
df_ijuridico['archivado'] = False
df_ijuridico['documento_origen_id'] = df_ijuridico['id_memo']
df_ijuridico.dropna(subset = ['codigo_final'], inplace = True)
df_ijuridico.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_ijuridico.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [885]:
df_ijuridico.to_sql('documento', con = engine, if_exists='append', index = False)

215

In [886]:
df_actoinicio = df_documentos.iloc[:, np.r_[0,36,45,46]].rename(columns={'INFORME FINAL ACTUACIÓN PREVIA':'codigo_if_ap'})
df_actoinicio = df_actoinicio.merge(df_memos_db, on='codigo_memo', how='left')
df_actoinicio = df_actoinicio.merge(df_iF_ap_db, on='codigo_if_ap', how='left')
df_actoinicio.rename(columns = {
    'ACTO DE INICIO PAS': 'codigo_final',
    'FECHA ACTO DE INICIO PAS': 'fecha_documento'
}, inplace = True)
df_actoinicio['tipo_documento_id'] = 6
df_actoinicio['es_manual'] = True
df_actoinicio['archivado'] = False
df_actoinicio['documento_origen_id'] = df_actoinicio['id']
df_actoinicio['documento_origen_id'] = df_actoinicio['documento_origen_id'].fillna(df_actoinicio['tramite_id'])
df_actoinicio.dropna(subset = ['codigo_final'], inplace = True)
df_actoinicio.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_actoinicio.drop(columns=['codigo_memo', 'id_memo', 'codigo_if_ap', 'id'], inplace = True)

In [887]:
df_actoinicio.to_sql('documento', con = engine, if_exists='append', index = False)

557

In [888]:
df_ai_db = pd.read_sql('select id, codigo_final as codigo_ai from documento where tipo_documento_id = 6', engine)

In [889]:
df_of_ai = df_documentos.iloc[:, np.r_[0,45,47,48]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_of_ai = df_of_ai.merge(df_memos_db, on='codigo_memo', how='left')
df_of_ai = df_of_ai.merge(df_ai_db, on='codigo_ai', how='left')
df_of_ai.rename(columns = {
    'OFICIO NOTIFICACIÓN': 'codigo_final',
    'FECHA OFICIO NOTIFICACIÓN': 'fecha_documento'
}, inplace = True)
df_of_ai['tipo_documento_id'] = 12
df_of_ai['subtipo_documento_id'] = 13
df_of_ai['es_manual'] = True
df_of_ai['archivado'] = False
df_of_ai['documento_origen_id'] = df_of_ai['id']
df_of_ai.dropna(subset = ['codigo_final'], inplace = True)
df_of_ai.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_of_ai.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai', 'id'], inplace = True)

In [890]:
df_of_ai.to_sql('documento', con = engine, if_exists='append', index = False)

373

In [891]:
df_mem_ai = df_documentos.iloc[:, np.r_[0,45,49,50]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_mem_ai = df_mem_ai.replace(['-','---','--', 'ARCOTEL-CZO2-2020-0341-M'],None)
df_mem_ai = df_mem_ai.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_ai = df_mem_ai.merge(df_ai_db, on='codigo_ai', how='left')
df_mem_ai.rename(columns = {
    'MEMORANDO PRUEBA DE NOTIFICACIÓN': 'codigo_final',
    'FECHA MEMORANDO PRUEBA DE NOTIFICACIÓN': 'fecha_documento'
}, inplace = True)
df_mem_ai['tipo_documento_id'] = 13
df_mem_ai['subtipo_documento_id'] = 15
df_mem_ai['es_manual'] = True
df_mem_ai['archivado'] = False
df_mem_ai['documento_origen_id'] = df_mem_ai['id']
df_mem_ai.dropna(subset = ['codigo_final'], inplace = True)
df_mem_ai.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_ai.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai', 'id'], inplace = True)

df_mem_ai['codigo_final'] = df_mem_ai['codigo_final'].astype(str).str.split('\n')
df_mem_ai['fecha_documento'] = df_mem_ai['fecha_documento'].astype(str).str.split('\n')

df_mem_ai = df_mem_ai.explode(['codigo_final', 'fecha_documento'])

df_mem_ai['codigo_final'] = df_mem_ai['codigo_final'].str.strip()
df_mem_ai['fecha_documento'] = df_mem_ai['fecha_documento'].str.strip()

df_mem_ai['fecha_documento'] = df_mem_ai['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_mem_ai['fecha_documento'] = df_mem_ai['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')
for esp, ing in meses.items():
    df_mem_ai['fecha_documento'] = df_mem_ai['fecha_documento'].astype(str).str.replace(esp, ing)
df_mem_ai['fecha_documento'] = pd.to_datetime(df_mem_ai['fecha_documento'], format='mixed')

In [892]:
df_mem_ai.to_sql('documento', con = engine, if_exists='append', index = False)

217

In [893]:
df_r_prestador = df_documentos.iloc[:, np.r_[0,45,53,54]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_r_prestador = df_r_prestador.replace(['--','NO','No responde','No contestó', 'No contesta'],None)
df_r_prestador = df_r_prestador.merge(df_memos_db, on='codigo_memo', how='left')
df_r_prestador = df_r_prestador.merge(df_ai_db, on='codigo_ai', how='left')
df_r_prestador.rename(columns = {
    'RESPUESTA PRESTADOR': 'codigo_final',
    'FECHA_1': 'fecha_documento'
}, inplace = True)
df_r_prestador['tipo_documento_id'] = 14
df_r_prestador['subtipo_documento_id'] = 21
df_r_prestador['es_manual'] = True
df_r_prestador['archivado'] = False
df_r_prestador['documento_origen_id'] = df_r_prestador['id']
df_r_prestador.dropna(subset = ['codigo_final'], inplace = True)
df_r_prestador.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_r_prestador.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai', 'id'], inplace = True)

df_r_prestador['codigo_final'] = df_r_prestador['codigo_final'].astype(str).str.split('\n')
df_r_prestador['fecha_documento'] = df_r_prestador['fecha_documento'].astype(str).str.split('\n')

#Correccion
df_r_prestador.at[126, 'codigo_final'].pop(-1)
df_r_prestador.at[158, 'fecha_documento'] = ['','']
df_r_prestador.at[170, 'fecha_documento'].append('')

len_docs = df_r_prestador['codigo_final'].str.len()
len_fechas = df_r_prestador['fecha_documento'].str.len()

df_r_prestador = df_r_prestador.explode(['codigo_final', 'fecha_documento'])

df_r_prestador['codigo_final'] = df_r_prestador['codigo_final'].str.strip()
df_r_prestador['fecha_documento'] = df_r_prestador['fecha_documento'].str.strip()

df_r_prestador['fecha_documento'] = df_r_prestador['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_r_prestador['fecha_documento'] = df_r_prestador['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')
for esp, ing in meses.items():
    df_r_prestador['fecha_documento'] = df_r_prestador['fecha_documento'].astype(str).str.replace(esp, ing)
df_r_prestador['fecha_documento'] = pd.to_datetime(df_r_prestador['fecha_documento'], format='mixed')

In [894]:
df_r_prestador.to_sql('documento', con = engine, if_exists='append', index = False)

272

In [895]:
df_pr_evp = df_documentos.iloc[:, np.r_[0,45,55,56]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_pr_evp = df_pr_evp.replace(['--','NO'],None)
df_pr_evp = df_pr_evp.merge(df_memos_db, on='codigo_memo', how='left')
df_pr_evp = df_pr_evp.merge(df_ai_db, on='codigo_ai', how='left')
df_pr_evp.rename(columns = {
    'PROVIDENCIA EVACUACIÓN PRUEBAS': 'codigo_final',
    'FECHA PROVIDENCIA EVACUACIÓN PRUEBAS': 'fecha_documento'
}, inplace = True)
df_pr_evp['tipo_documento_id'] = 7
df_pr_evp['subtipo_documento_id'] = 8
df_pr_evp['es_manual'] = True
df_pr_evp['archivado'] = False
df_pr_evp['documento_origen_id'] = df_pr_evp['id']
df_pr_evp.dropna(subset = ['codigo_final'], inplace = True)
df_pr_evp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_pr_evp.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai', 'id'], inplace = True)

In [896]:
df_pr_evp.to_sql('documento', con = engine, if_exists='append', index = False)

273

In [897]:
df_pr_evp_df = pd.read_sql('select id, codigo_final as codigo_pr_env from documento where tipo_documento_id = 7 and subtipo_documento_id = 8', engine)

In [898]:
df_of_pr_evp = df_documentos.iloc[:, np.r_[0,55,57,58]].rename(columns={'PROVIDENCIA EVACUACIÓN PRUEBAS':'codigo_pr_env'})
df_of_pr_evp = df_of_pr_evp.replace(['--','NO'],None)
df_of_pr_evp = df_of_pr_evp.merge(df_memos_db, on='codigo_memo', how='left')
df_of_pr_evp = df_of_pr_evp.merge(df_pr_evp_df, on='codigo_pr_env', how='left')
df_of_pr_evp.rename(columns = {
    'OFICIO NOTIFICACION PROVIDENCIA': 'codigo_final',
    'FECHA OFICIO NOTIFICACIÓN PROVIDENCIA': 'fecha_documento'
}, inplace = True)
df_of_pr_evp['tipo_documento_id'] = 12
df_of_pr_evp['subtipo_documento_id'] = 13
df_of_pr_evp['es_manual'] = True
df_of_pr_evp['archivado'] = False
df_of_pr_evp['documento_origen_id'] = df_of_pr_evp['id']
df_of_pr_evp.dropna(subset = ['codigo_final'], inplace = True)
df_of_pr_evp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_of_pr_evp.drop(columns=['codigo_memo', 'id_memo', 'codigo_pr_env', 'id'], inplace = True)

df_of_pr_evp['codigo_final'] = df_of_pr_evp['codigo_final'].astype(str).str.split('\n')
df_of_pr_evp['fecha_documento'] = df_of_pr_evp['fecha_documento'].astype(str).str.split('\n')

len_docs = df_of_pr_evp['codigo_final'].str.len()
len_fechas = df_of_pr_evp['fecha_documento'].str.len()

df_of_pr_evp = df_of_pr_evp.explode(['codigo_final', 'fecha_documento'])

df_of_pr_evp['codigo_final'] = df_of_pr_evp['codigo_final'].str.strip()
df_of_pr_evp['fecha_documento'] = df_of_pr_evp['fecha_documento'].str.strip()

df_of_pr_evp['fecha_documento'] = df_of_pr_evp['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_of_pr_evp['fecha_documento'] = df_of_pr_evp['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')

for esp, ing in meses.items():
    df_of_pr_evp['fecha_documento'] = df_of_pr_evp['fecha_documento'].astype(str).str.replace(esp, ing)
df_of_pr_evp['fecha_documento'] = pd.to_datetime(df_of_pr_evp['fecha_documento'], format='mixed')
df_of_pr_evp

,codigo_final,fecha_documento,tramite_id,tipo_documento_id,subtipo_documento_id,es_manual,archivado,documento_origen_id
164,ARCOTEL-CZO2-2022-0406-OF,2022-06-28,165,12,13,True,False,11567.0
199,ARCOTEL-CZO2-2022-0337-OF,2022-06-02,200,12,13,True,False,11570.0
200,ARCOTEL-CZO2-2022-0354-OF,2022-06-08,201,12,13,True,False,11571.0
201,ARCOTEL-CZO2-2023-0508-OF,2023-12-14,202,12,13,True,False,11572.0
211,ARCOTEL-CZO2-2022-0257-OF,2022-04-28,212,12,13,True,False,11576.0
...,...,...,...,...,...,...,...,...
1481,ARCOTEL-CZO2-2025-0357-OF,2025-10-08,1482,12,13,True,False,11807.0
1491,ARCOTEL-CZO2-2025-0356-OF,2025-10-08,1492,12,13,True,False,11808.0
1575,ARCOTEL-CZO2-2025-0015-OF,2025-01-20,1576,12,13,True,False,11809.0
1936,ARCOTEL-CZO2-2025-0367-OF,2025-10-14,1936,12,13,True,False,11811.0
2215,ARCOTEL-CZO2-2025-0370-OF,2025-10-15,2216,12,13,True,False,11823.0

In [899]:
df_of_pr_evp.to_sql('documento', con = engine, if_exists='append', index = False)

147

In [900]:
df_mem_pr_evp = df_documentos.iloc[:, np.r_[0,55,59,60]].rename(columns={'PROVIDENCIA EVACUACIÓN PRUEBAS':'codigo_pr_env'})
df_mem_pr_evp = df_mem_pr_evp.replace(['--','NO'],None)
df_mem_pr_evp = df_mem_pr_evp.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_pr_evp = df_mem_pr_evp.merge(df_pr_evp_df, on='codigo_pr_env', how='left')
df_mem_pr_evp.rename(columns = {
    'MEMORANDO PRUEBA DE NOTIFICACIÓN.1': 'codigo_final',
    'FECHA MEMORANDO PRUEBA DE NOTIFICACIÓN.1': 'fecha_documento'
}, inplace = True)
df_mem_pr_evp['tipo_documento_id'] = 13
df_mem_pr_evp['subtipo_documento_id'] = 15
df_mem_pr_evp['es_manual'] = True
df_mem_pr_evp['archivado'] = False
df_mem_pr_evp['documento_origen_id'] = df_mem_pr_evp['id']
df_mem_pr_evp.dropna(subset = ['codigo_final'], inplace = True)
df_mem_pr_evp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_pr_evp.drop(columns=['codigo_memo', 'id_memo', 'codigo_pr_env', 'id'], inplace = True)

df_mem_pr_evp['codigo_final'] = df_mem_pr_evp['codigo_final'].astype(str).str.strip().str.split('\n')
df_mem_pr_evp['fecha_documento'] = df_mem_pr_evp['fecha_documento'].astype(str).str.strip().str.split('\n')

#correcciones
df_r_prestador.at[265, 'fecha_documento'] = ['']
hax_f = df_mem_pr_evp['codigo_final'][302]
df_mem_pr_evp.loc[302, 'codigo_final'] = df_mem_pr_evp['fecha_documento'][302] 
df_mem_pr_evp.loc[302, 'fecha_documento'] = hax_f

df_mem_pr_evp = df_mem_pr_evp.explode(['codigo_final', 'fecha_documento'])

df_mem_pr_evp['codigo_final'] = df_mem_pr_evp['codigo_final'].str.strip()
df_mem_pr_evp['fecha_documento'] = df_mem_pr_evp['fecha_documento'].str.strip()

df_mem_pr_evp['fecha_documento'] = df_mem_pr_evp['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_mem_pr_evp['fecha_documento'] = df_mem_pr_evp['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')
df_mem_pr_evp['fecha_documento'] = df_mem_pr_evp['fecha_documento'].astype(str).str.lower().str.replace('20201', '2021')

for esp, ing in meses.items():
    df_mem_pr_evp['fecha_documento'] = df_mem_pr_evp['fecha_documento'].astype(str).str.replace(esp, ing)
    
df_mem_pr_evp['fecha_documento'] = pd.to_datetime(df_mem_pr_evp['fecha_documento'], format='mixed')

In [901]:
df_mem_pr_evp.to_sql('documento', con = engine, if_exists='append', index = False)

198

In [902]:
df_mem_dya = df_documentos.iloc[:, np.r_[0,62,63]]
df_mem_dya = df_mem_dya.replace(['--','NO','.NO'],None)
df_mem_dya = df_mem_dya.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_dya.rename(columns = {
    'MEMORANDO A UNIDAD DE DOCUMENTACIÓN Y ARCHIVO': 'codigo_final',
    'FECHA_2': 'fecha_documento'
}, inplace = True)
df_mem_dya['tipo_documento_id'] = 13
df_mem_dya['subtipo_documento_id'] = 16
df_mem_dya['es_manual'] = True
df_mem_dya['archivado'] = False
df_mem_dya['documento_origen_id'] = df_mem_dya['id_memo']

#correccion
df_mem_dya.loc[127, 'codigo_final'] = np.nan

df_mem_dya.dropna(subset = ['codigo_final'], inplace = True)
df_mem_dya.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_dya.drop(columns=['codigo_memo' ,'id_memo'], inplace = True)

df_mem_dya['codigo_final'] = df_mem_dya['codigo_final'].astype(str).str.strip().str.split('\n')
df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.strip().str.split('\n')


df_mem_dya = df_mem_dya.explode(['codigo_final', 'fecha_documento'])

df_mem_dya['codigo_final'] = df_mem_dya['codigo_final'].astype(str).str.strip().str.split(' / ')
df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.strip().str.split(' / ')

df_mem_dya = df_mem_dya.explode(['codigo_final', 'fecha_documento'])

df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')
df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.lower().str.replace(' e ', ' ')
df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.lower().str.replace('d e', ' ')
df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.lower().str.replace('amyo', 'May')

for esp, ing in meses.items():
    df_mem_dya['fecha_documento'] = df_mem_dya['fecha_documento'].astype(str).str.replace(esp, ing)

df_mem_dya['fecha_documento'] = pd.to_datetime(df_mem_dya['fecha_documento'], format='mixed')

In [903]:
df_mem_dya.to_sql('documento', con = engine, if_exists='append', index = False)

248

In [904]:
df_mem_r_dya = df_documentos.iloc[:, np.r_[0,64,65]]
df_mem_r_dya = df_mem_r_dya.replace(['--','NO','.NO'],None)
df_mem_r_dya = df_mem_r_dya.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_r_dya.rename(columns = {
    'MEMORANDO RESPUESTA DE  DOCUMENTACIÓN Y ARCHIVO': 'codigo_final',
    'FECHA MEMORANDO RESPUESTA DE  DOCUMENTACIÓN Y ARCHIVO': 'fecha_documento'
}, inplace = True)
df_mem_r_dya['tipo_documento_id'] = 13
df_mem_r_dya['subtipo_documento_id'] = 25
df_mem_r_dya['es_manual'] = True
df_mem_r_dya['archivado'] = False
df_mem_r_dya['documento_origen_id'] = df_mem_r_dya['id_memo']
df_mem_r_dya.dropna(subset = ['codigo_final'], inplace = True)
df_mem_r_dya.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_r_dya.drop(columns=['codigo_memo' ,'id_memo'], inplace = True)

In [905]:
df_mem_r_dya.to_sql('documento', con = engine, if_exists='append', index = False)

235

In [906]:
df_mem_odu = df_documentos.iloc[:, np.r_[0,66,67]]
df_mem_odu = df_mem_odu.replace(['--','---','NO','.NO'],None)
df_mem_odu = df_mem_odu.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_odu.rename(columns = {
    'OTROS MEMORANDOS A DEDA Y A OTRAS UNIDADES': 'codigo_final',
    'FECHA  - OTROS MEMORANDOS A DEDA Y A OTRAS UNIDADES': 'fecha_documento'
}, inplace = True)
df_mem_odu['tipo_documento_id'] = 13
df_mem_odu['subtipo_documento_id'] = 17
df_mem_odu['es_manual'] = True
df_mem_odu['archivado'] = False
df_mem_odu['documento_origen_id'] = df_mem_odu['id_memo']
df_mem_odu.dropna(subset = ['codigo_final'], inplace = True)
df_mem_odu.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_odu.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

df_mem_odu['codigo_final'] = df_mem_odu['codigo_final'].astype(str).str.replace('\nd', ' d')

df_mem_odu['codigo_final'] = df_mem_odu['codigo_final'].astype(str).str.strip().str.split('\n')
df_mem_odu['fecha_documento'] = df_mem_odu['fecha_documento'].astype(str).str.strip().str.split('\n')

idx1 = [223, 248, 259, 260, 261, 279, 304, 325, 353, 367, 402, 403, 412, 478, 589,
        590, 593, 597, 598, 599, 618, 624, 625, 626, 627, 669, 748, 754, 764, 766]
idx2 = [372, 419, 464, 475, 617, 780]
idx3 = [445, 670]
idx4 = [420]
idx5 = [446, 671, 487]

for i in idx1:
    df_mem_odu.at[i, 'fecha_documento'] = ['']

for i in idx2:
    df_mem_odu.at[i, 'fecha_documento'] = ['']*2

for i in idx3:
    df_mem_odu.at[i, 'fecha_documento'] = ['']*3

for i in idx4:
    df_mem_odu.at[i, 'fecha_documento'] = ['']*4

for i in idx5:
    df_mem_odu.at[i, 'fecha_documento'] = ['']*5

df_mem_odu = df_mem_odu.explode(['codigo_final', 'fecha_documento'])

df_mem_odu['fecha_documento'] = df_mem_odu['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_mem_odu['fecha_documento'] = df_mem_odu['fecha_documento'].astype(str).str.replace(esp, ing)

df_mem_odu['fecha_documento'] = pd.to_datetime(df_mem_odu['fecha_documento'], format='mixed')

In [907]:
df_mem_odu.to_sql('documento', con = engine, if_exists='append', index = False)

157

In [908]:
df_mem_r_odu = df_documentos.iloc[:, np.r_[0,68,69]]
df_mem_r_odu = df_mem_r_odu.replace(['--', '---','NO','.NO'],None)
df_mem_r_odu = df_mem_r_odu.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_r_odu.rename(columns = {
    'RESPUESTA A OTROS MEMORANDOS DE DEDA Y DE OTRAS UNIDADES': 'codigo_final',
    'FECHA - RESPUESTA A OTROS MEMORANDOS DE DEDA Y DE OTRAS UNIDADES': 'fecha_documento'
}, inplace = True)
df_mem_r_odu['tipo_documento_id'] = 13
df_mem_r_odu['subtipo_documento_id'] = 26
df_mem_r_odu['es_manual'] = True
df_mem_r_odu['archivado'] = False
df_mem_r_odu['documento_origen_id'] = df_mem_r_odu['id_memo']
df_mem_r_odu.dropna(subset = ['codigo_final'], inplace = True)
df_mem_r_odu.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_r_odu.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

df_mem_r_odu['fecha_documento'] = df_mem_r_odu['fecha_documento'].astype(str).str.lower().str.replace(' - ', '\n')
df_mem_r_odu['fecha_documento'] = df_mem_r_odu['fecha_documento'].astype(str).str.lower().str.replace(' / ', '\n')
df_mem_r_odu['codigo_final'] = df_mem_r_odu['codigo_final'].astype(str).str.lower().str.replace('/', '\n')
df_mem_r_odu['codigo_final'] = df_mem_r_odu['codigo_final'].astype(str).str.lower().str.replace(' / ', '\n')

df_mem_r_odu['codigo_final'] = df_mem_r_odu['codigo_final'].astype(str).str.strip().str.split('\n')
df_mem_r_odu['fecha_documento'] = df_mem_r_odu['fecha_documento'].astype(str).str.strip().str.split('\n')

df_mem_r_odu.at[353, 'fecha_documento'] = ['','','','','','','','','','']
df_mem_r_odu.at[354, 'fecha_documento'] = ['','']
df_mem_r_odu.at[402, 'fecha_documento'] = ['','']
df_mem_r_odu.at[419, 'fecha_documento'] = ['','']
df_mem_r_odu.at[420, 'fecha_documento'] = ['','','','']
df_mem_r_odu.at[463, 'codigo_final'].pop(0)
df_mem_r_odu.at[780, 'fecha_documento'].append('')

df_mem_r_odu = df_mem_r_odu.explode(['codigo_final', 'fecha_documento'])

hax_f = df_mem_r_odu['codigo_final'][780]
df_mem_r_odu.loc[780, 'codigo_final'] = df_mem_r_odu['fecha_documento'][780] 
df_mem_r_odu.loc[780, 'fecha_documento'] = hax_f

df_mem_r_odu['fecha_documento'] = df_mem_r_odu['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_mem_r_odu['fecha_documento'] = df_mem_r_odu['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')

for esp, ing in meses.items():
    df_mem_r_odu['fecha_documento'] = df_mem_r_odu['fecha_documento'].astype(str).str.replace(esp, ing)

df_mem_r_odu['fecha_documento'] = pd.to_datetime(df_mem_r_odu['fecha_documento'], format='mixed')

In [909]:
df_mem_r_odu.to_sql('documento', con = engine, if_exists='append', index = False)

146

In [910]:
df_mem_ge = df_documentos.iloc[:, np.r_[0,70,71]]
df_mem_ge = df_mem_ge.replace(['--','NO','.NO'],None)
df_mem_ge = df_mem_ge.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_ge.rename(columns = {
    'MEMORANDO A GESTIÓN ECONÓNICA': 'codigo_final',
    'FECHA MEMORANDO A GESTIÓN ECONÓNICA': 'fecha_documento'
}, inplace = True)
df_mem_ge['tipo_documento_id'] = 13
df_mem_ge['subtipo_documento_id'] = 18
df_mem_ge['es_manual'] = True
df_mem_ge['archivado'] = False
df_mem_ge['documento_origen_id'] = df_mem_ge['id_memo']
df_mem_ge.dropna(subset = ['codigo_final'], inplace = True)
df_mem_ge.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_ge.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [911]:
df_mem_ge.to_sql('documento', con = engine, if_exists='append', index = False)

253

In [912]:
df_mem_r_ge = df_documentos.iloc[:, np.r_[0,72,73]]
df_mem_r_ge = df_mem_r_ge.replace(['--','NO','.NO'],None)
df_mem_r_ge = df_mem_r_ge.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_r_ge.rename(columns = {
    'RESPUESTA DE GESTIÓN ECONÓNICA': 'codigo_final',
    'FECHA RESPUESTA DE GESTIÓN ECONÓNICA': 'fecha_documento'
}, inplace = True)
df_mem_r_ge['tipo_documento_id'] = 13
df_mem_r_ge['subtipo_documento_id'] = 27
df_mem_r_ge['es_manual'] = True
df_mem_r_ge['archivado'] = False
df_mem_r_ge['documento_origen_id'] = df_mem_r_ge['id_memo']
df_mem_r_ge.dropna(subset = ['codigo_final'], inplace = True)
df_mem_r_ge.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_r_ge.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [913]:
df_mem_r_ge.to_sql('documento', con = engine, if_exists='append', index = False)

256

In [914]:
df_mem_st = df_documentos.iloc[:, np.r_[0,74,75]]
df_mem_st = df_mem_st.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_mem_st = df_mem_st.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_st.rename(columns = {
    'MEMORANDO A SERVIDOR TÉCNICO': 'codigo_final',
    'FECHA MEMORANDO A SERVIDOR TÉCNICO': 'fecha_documento'
}, inplace = True)
df_mem_st['tipo_documento_id'] = 13
df_mem_st['subtipo_documento_id'] = 20
df_mem_st['es_manual'] = True
df_mem_st['archivado'] = False
df_mem_st['documento_origen_id'] = df_mem_st['id_memo']
df_mem_st.dropna(subset = ['codigo_final'], inplace = True)
df_mem_st.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_st.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

df_mem_st['codigo_final'] = df_mem_st['codigo_final'].astype(str).str.replace('\n(', ' (')

df_mem_st['codigo_final'] = df_mem_st['codigo_final'].astype(str).str.strip().str.split('\n')
df_mem_st['fecha_documento'] = df_mem_st['fecha_documento'].astype(str).str.strip().str.split('\n')

df_mem_st = df_mem_st.explode(['codigo_final', 'fecha_documento'])

df_mem_st['codigo_final'] = df_mem_st['codigo_final'].astype(str).str.strip().str.split(' / ')
df_mem_st['fecha_documento'] = df_mem_st['fecha_documento'].astype(str).str.strip().str.split(' / ')

df_mem_st = df_mem_st.explode(['codigo_final', 'fecha_documento'])

df_mem_st['fecha_documento'] = df_mem_st['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')
df_mem_st['fecha_documento'] = df_mem_st['fecha_documento'].astype(str).str.lower().str.replace(' del ', ' ')
df_mem_st['fecha_documento'] = df_mem_st['fecha_documento'].astype(str).str.lower().str.replace('d e', ' ')

for esp, ing in meses.items():
    df_mem_st['fecha_documento'] = df_mem_st['fecha_documento'].astype(str).str.replace(esp, ing)

df_mem_st['fecha_documento'] = pd.to_datetime(df_mem_st['fecha_documento'], format='mixed')

In [915]:
df_mem_st.to_sql('documento', con = engine, if_exists='append', index = False)

197

In [916]:
df_2_it = df_documentos.iloc[:, np.r_[0,77,78]]
df_2_it = df_2_it.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_2_it = df_2_it.merge(df_memos_db, on='codigo_memo', how='left')
df_2_it.rename(columns = {
    'No. INFORME TÉCNICO': 'codigo_final',
    'FECHA_IT': 'fecha_documento'
}, inplace = True)
df_2_it['tipo_documento_id'] = 3
df_2_it['es_manual'] = True
df_2_it['archivado'] = False
df_2_it['documento_origen_id'] = df_2_it['id_memo']
df_2_it.dropna(subset = ['codigo_final'], inplace = True)
df_2_it.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_2_it.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [917]:
df_2_it.to_sql('documento', con = engine, if_exists='append', index = False)

291

In [918]:
df_mem_sj = df_documentos.iloc[:, np.r_[0,79,80]]
df_mem_sj = df_mem_sj.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_mem_sj = df_mem_sj.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_sj.rename(columns = {
    'MEMORANDO A SERVIDOR JURÍDICO': 'codigo_final',
    'FECHA MEMORANDO A SERVIDOR JURÍDICO': 'fecha_documento'
}, inplace = True)
df_mem_sj['tipo_documento_id'] = 13
df_mem_sj['subtipo_documento_id'] = 19
df_mem_sj['es_manual'] = True
df_mem_sj['archivado'] = False
df_mem_sj['documento_origen_id'] = df_mem_sj['id_memo']
df_mem_sj.dropna(subset = ['codigo_final'], inplace = True)
df_mem_sj.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_sj.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [919]:
df_mem_sj.to_sql('documento', con = engine, if_exists='append', index = False)

279

In [920]:
df_ij_ins = df_documentos.iloc[:, np.r_[0,81,82]]
df_ij_ins = df_ij_ins.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_ij_ins = df_ij_ins.merge(df_memos_db, on='codigo_memo', how='left')
df_ij_ins.rename(columns = {
    'No. INFORME JURÍDICO - INSTRUCCIÓN': 'codigo_final',
    'FECHA INFORME JURÍDICO - INSTRUCCIÓN': 'fecha_documento'
}, inplace = True)
df_ij_ins['tipo_documento_id'] =11
df_ij_ins['subtipo_documento_id'] = 10
df_ij_ins['es_manual'] = True
df_ij_ins['archivado'] = False
df_ij_ins['documento_origen_id'] = df_ij_ins['id_memo']
df_ij_ins.dropna(subset = ['codigo_final'], inplace = True)
df_ij_ins.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_ij_ins.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [921]:
df_ij_ins.to_sql('documento', con = engine, if_exists='append', index = False)

391

In [922]:
df_pr_na = df_documentos.iloc[:, np.r_[0,45,83,84]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_pr_na = df_pr_na.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_pr_na = df_pr_na.merge(df_memos_db, on='codigo_memo', how='left')
df_pr_na = df_pr_na.merge(df_ai_db, on='codigo_ai', how='left')
df_pr_na.rename(columns = {
    'PROVIDENCIA NOTIFICANDO LO ACTUADO': 'codigo_final',
    'FECHA PROVIDENCIA NOTIFICANDO LO ACTUADO': 'fecha_documento'
}, inplace = True)
df_pr_na['tipo_documento_id'] =7
df_pr_na['subtipo_documento_id'] = 5
df_pr_na['es_manual'] = True
df_pr_na['archivado'] = False
df_pr_na['documento_origen_id'] = df_pr_na['id']
df_pr_na.dropna(subset = ['codigo_final'], inplace = True)
df_pr_na.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_pr_na.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai', 'id'], inplace = True)

In [923]:
df_pr_na.to_sql('documento', con = engine, if_exists='append', index = False)

90

In [924]:
df_pr_ctp = df_documentos.iloc[:, np.r_[0,45,85,86]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_pr_ctp = df_pr_ctp.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_pr_ctp = df_pr_ctp.merge(df_memos_db, on='codigo_memo', how='left')
df_pr_ctp = df_pr_ctp.merge(df_ai_db, on='codigo_ai', how='left')
df_pr_ctp.rename(columns = {
    'PROVIDENCIA CIERRE DE TÉRMINO DE PRUEBA': 'codigo_final',
    'FECHA PROVIDENCIA CIERRE DE TÉRMINO DE PRUEBA': 'fecha_documento'
}, inplace = True)
df_pr_ctp['tipo_documento_id'] =7
df_pr_ctp['subtipo_documento_id'] = 6
df_pr_ctp['es_manual'] = True
df_pr_ctp['archivado'] = False
df_pr_ctp['documento_origen_id'] = df_pr_ctp['id']
df_pr_ctp.dropna(subset = ['codigo_final'], inplace = True)
df_pr_ctp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_pr_ctp.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai','id'], inplace = True)

In [925]:
df_pr_ctp.to_sql('documento', con = engine, if_exists='append', index = False)

230

In [926]:
df_pr_ctp_db = pd.read_sql('select id, codigo_final as codigo_pr_ctp from documento where tipo_documento_id = 7 and subtipo_documento_id = 6', engine)

In [927]:
df_of_pr_ctp = df_documentos.iloc[:, np.r_[0,85,87,88]].rename(columns={'PROVIDENCIA CIERRE DE TÉRMINO DE PRUEBA':'codigo_pr_ctp'})
df_of_pr_ctp = df_of_pr_ctp.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_of_pr_ctp = df_of_pr_ctp.merge(df_memos_db, on='codigo_memo', how='left')
df_of_pr_ctp = df_of_pr_ctp.merge(df_pr_ctp_db, on='codigo_pr_ctp', how='left')
df_of_pr_ctp.rename(columns = {
    'OFICIO DE PROVIDENCIA DE CIERRE DE PRUEBA': 'codigo_final',
    'FECHA DE OFICIO DE CIERRE DE PRUEBA': 'fecha_documento'
}, inplace = True)
df_of_pr_ctp['tipo_documento_id'] =12
df_of_pr_ctp['subtipo_documento_id'] = 13
df_of_pr_ctp['es_manual'] = True
df_of_pr_ctp['archivado'] = False
df_of_pr_ctp['documento_origen_id'] = df_of_pr_ctp['id']
df_of_pr_ctp.dropna(subset = ['codigo_final'], inplace = True)
df_of_pr_ctp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_of_pr_ctp.drop(columns=['codigo_memo','id_memo','codigo_pr_ctp','id'], inplace = True)

df_of_pr_ctp['fecha_documento'] = df_of_pr_ctp['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_of_pr_ctp['fecha_documento'] = df_of_pr_ctp['fecha_documento'].astype(str).str.replace(esp, ing)

df_of_pr_ctp['fecha_documento'] = pd.to_datetime(df_of_pr_ctp['fecha_documento'], format='mixed')

In [928]:
df_of_pr_ctp.to_sql('documento', con = engine, if_exists='append', index = False)

113

In [929]:
df_mem_pr_ctp = df_documentos.iloc[:, np.r_[0,85,89,90]].rename(columns={'PROVIDENCIA CIERRE DE TÉRMINO DE PRUEBA':'codigo_pr_ctp'})
df_mem_pr_ctp = df_mem_pr_ctp.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_mem_pr_ctp = df_mem_pr_ctp.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_pr_ctp = df_mem_pr_ctp.merge(df_pr_ctp_db, on='codigo_pr_ctp', how='left')
df_mem_pr_ctp.rename(columns = {
    'MEMORANDO DE NOTIFICACIÓN DE CIERRE DE PRUEBA': 'codigo_final',
    'FECHA DE MEMORANDO DE NOTIFICACIÓN DE CIERRE DE PRUEBA': 'fecha_documento'
}, inplace = True)
df_mem_pr_ctp['tipo_documento_id'] =13
df_mem_pr_ctp['subtipo_documento_id'] = 14
df_mem_pr_ctp['es_manual'] = True
df_mem_pr_ctp['archivado'] = False
df_mem_pr_ctp['documento_origen_id'] = df_mem_pr_ctp['id']
df_mem_pr_ctp.dropna(subset = ['codigo_final'], inplace = True)
df_mem_pr_ctp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_pr_ctp.drop(columns=['codigo_memo','id_memo','codigo_pr_ctp','id'], inplace = True)

df_mem_pr_ctp['fecha_documento'] = df_mem_pr_ctp['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_mem_pr_ctp['fecha_documento'] = df_mem_pr_ctp['fecha_documento'].astype(str).str.replace(esp, ing)

df_mem_pr_ctp['fecha_documento'] = pd.to_datetime(df_mem_pr_ctp['fecha_documento'], format='mixed')

In [930]:
df_mem_pr_ctp.to_sql('documento', con = engine, if_exists='append', index = False)

82

In [931]:
df_pr_ri = df_documentos.iloc[:, np.r_[0,91,92]]
df_pr_ri = df_pr_ri.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_pr_ri = df_pr_ri.merge(df_memos_db, on='codigo_memo', how='left')
df_pr_ri.rename(columns = {
    'PROVIDENCIA REMITE INFORMES IJ e IT': 'codigo_final',
    'FECHA PROVIDENCIA REMITE INFORMES IJ e IT': 'fecha_documento'
}, inplace = True)
df_pr_ri['tipo_documento_id'] = 7
df_pr_ri['subtipo_documento_id'] = 7
df_pr_ri['es_manual'] = True
df_pr_ri['archivado'] = False
df_pr_ri['documento_origen_id'] = df_pr_ri['id_memo']
df_pr_ri.dropna(subset = ['codigo_final'], inplace = True)
df_pr_ri.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_pr_ri.drop(columns=['codigo_memo', 'id_memo'], inplace = True)

In [932]:
df_pr_ri.to_sql('documento', con = engine, if_exists='append', index = False)

115

In [933]:
df_dictamen = df_documentos.iloc[:, np.r_[0,45,93,94]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_dictamen = df_dictamen.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_dictamen = df_dictamen.merge(df_memos_db, on='codigo_memo', how='left')
df_dictamen = df_dictamen.merge(df_ai_db, on='codigo_ai', how='left')
df_dictamen.rename(columns = {
    'No. DICTAMEN': 'codigo_final',
    'FECHA DICTAMEN': 'fecha_documento'
}, inplace = True)
df_dictamen['tipo_documento_id'] = 8
df_dictamen['es_manual'] = True
df_dictamen['archivado'] = False
df_dictamen['documento_origen_id'] = df_dictamen['id']
df_dictamen.dropna(subset = ['codigo_final'], inplace = True)
df_dictamen.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_dictamen.drop(columns=['codigo_memo', 'id_memo', 'codigo_ai','id'], inplace = True)

df_dictamen['fecha_documento'] = df_dictamen['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_dictamen['fecha_documento'] = df_dictamen['fecha_documento'].astype(str).str.replace(esp, ing)

df_dictamen['fecha_documento'] = pd.to_datetime(df_dictamen['fecha_documento'], format='mixed')

In [934]:
df_dictamen.to_sql('documento', con = engine, if_exists='append', index = False)

415

In [935]:
df_d_db = pd.read_sql('select id, codigo_final as codigo_d from documento where tipo_documento_id = 8', engine)

In [936]:
df_mem_d = df_documentos.iloc[:, np.r_[0,93,95,96]].rename(columns={'No. DICTAMEN':'codigo_d'})
df_mem_d = df_mem_d.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_mem_d = df_mem_d.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_d = df_mem_d.merge(df_d_db, on='codigo_d', how='left')
df_mem_d.rename(columns = {
    'MEMORANDO DICTAMEN A CZO2 / PRESUNTO RESPONSABLE': 'codigo_final',
    'FECHA MEMORANDO DICTAMEN A CZO2 / PRESUNTO RESPONSABLE': 'fecha_documento'
}, inplace = True)
df_mem_d['tipo_documento_id'] =13
df_mem_d['subtipo_documento_id'] = 29
df_mem_d['es_manual'] = True
df_mem_d['archivado'] = False
df_mem_d['documento_origen_id'] = df_mem_d['id']
df_mem_d.dropna(subset = ['codigo_final'], inplace = True)
df_mem_d.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_d.drop(columns=['codigo_memo','id_memo','codigo_d','id'], inplace = True)

df_mem_d['codigo_final'] = df_mem_d['codigo_final'].astype(str).str.strip().str.split('\n')
df_mem_d['fecha_documento'] = df_mem_d['fecha_documento'].astype(str).str.strip().str.split('\n')

df_mem_d = df_mem_d.explode(['codigo_final', 'fecha_documento'])

df_mem_d['fecha_documento'] = df_mem_d['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_mem_d['fecha_documento'] = df_mem_d['fecha_documento'].astype(str).str.replace(esp, ing)

df_mem_d['fecha_documento'] = pd.to_datetime(df_mem_d['fecha_documento'], format='mixed')

In [937]:
df_mem_d.to_sql('documento', con = engine, if_exists='append', index = False)

154

In [938]:
df_pr_ep = df_documentos.iloc[:, np.r_[0,45,97,98]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_pr_ep = df_pr_ep.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_pr_ep = df_pr_ep.merge(df_memos_db, on='codigo_memo', how='left')
df_pr_ep = df_pr_ep.merge(df_ai_db, on='codigo_ai', how='left')
df_pr_ep.rename(columns = {
    'PROVIDENCIA EXTENSIÓN PLAZO': 'codigo_final',
    'PLAZO (meses)': 'plazo'
}, inplace = True)
df_pr_ep['tipo_documento_id'] = 7
df_pr_ep['subtipo_documento_id'] = 9
df_pr_ep['es_manual'] = True
df_pr_ep['archivado'] = False
df_pr_ep['documento_origen_id'] = df_pr_ep['id']
df_pr_ep.dropna(subset = ['codigo_final'], inplace = True)
df_pr_ep.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_pr_ep.drop(columns=['codigo_memo','id_memo','codigo_ai','id'], inplace = True)

In [939]:
df_pr_ep.to_sql('documento', con = engine, if_exists='append', index = False)

39

In [940]:
df_rpas = df_documentos.iloc[:, np.r_[0,45,100,101,102]].rename(columns={'ACTO DE INICIO PAS':'codigo_ai'})
df_rpas = df_rpas.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_rpas = df_rpas.merge(df_memos_db, on='codigo_memo', how='left')
df_rpas = df_rpas.merge(df_ai_db, on='codigo_ai', how='left')
df_rpas.rename(columns = {
    'No. RESOLUCIÓN': 'codigo_final',
    'FECHA RESOLUCIÓN': 'fecha_documento',
    'SANCIÓN': 'asunto'
}, inplace = True)
df_rpas['tipo_documento_id'] = 9
df_rpas['es_manual'] = True
df_rpas['archivado'] = False
df_rpas['documento_origen_id'] = df_rpas['id']
df_rpas.dropna(subset = ['codigo_final'], inplace = True)
df_rpas.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_rpas.drop(columns=['codigo_memo','id_memo','codigo_ai','id'], inplace = True)

In [941]:
df_rpas.to_sql('documento', con = engine, if_exists='append', index = False)

522

In [942]:
df_rpas_db = pd.read_sql('select id, codigo_final as codigo_rpas from documento where tipo_documento_id = 9', engine)

In [943]:
df_of_rpas = df_documentos.iloc[:, np.r_[0,100,103,104]].rename(columns={'No. RESOLUCIÓN':'codigo_rpas'})
df_of_rpas = df_of_rpas.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_of_rpas = df_of_rpas.merge(df_memos_db, on='codigo_memo', how='left')
df_of_rpas = df_of_rpas.merge(df_rpas_db, on='codigo_rpas', how='left')
df_of_rpas.rename(columns = {
    'OFICIO NOTIFICACIÓN RESOLUCIÓN': 'codigo_final',
    'FECHA OFICIO NOTIFICACIÓN RESOLUCIÓN': 'fecha_documento'
}, inplace = True)
df_of_rpas['tipo_documento_id'] = 12
df_of_rpas['subtipo_documento_id'] = 13
df_of_rpas['es_manual'] = True
df_of_rpas['archivado'] = False
df_of_rpas['documento_origen_id'] = df_of_rpas['id']
df_of_rpas.dropna(subset = ['codigo_final'], inplace = True)
df_of_rpas.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_of_rpas.drop(columns=['codigo_memo','id_memo','codigo_rpas','id'], inplace = True)

df_of_rpas['codigo_final'] = df_of_rpas['codigo_final'].astype(str).str.strip().str.split('\n')
df_of_rpas['fecha_documento'] = df_of_rpas['fecha_documento'].astype(str).str.strip().str.split('\n')

df_of_rpas = df_of_rpas.explode(['codigo_final', 'fecha_documento'])

df_of_rpas['fecha_documento'] = df_of_rpas['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_of_rpas['fecha_documento'] = df_of_rpas['fecha_documento'].astype(str).str.replace(esp, ing)

df_of_rpas.loc[335, 'fecha_documento'] = '14 October 2020'
df_of_rpas.loc[1345, 'fecha_documento'] = '17/7/2025'

df_of_rpas['fecha_documento'] = pd.to_datetime(df_of_rpas['fecha_documento'], format='mixed')

In [944]:
df_of_rpas.to_sql('documento', con = engine, if_exists='append', index = False)

356

In [945]:
df_mem_rpas = df_documentos.iloc[:, np.r_[0,100,106,107]].rename(columns={'No. RESOLUCIÓN':'codigo_rpas'})
df_mem_rpas = df_mem_rpas.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_mem_rpas = df_mem_rpas.merge(df_memos_db, on='codigo_memo', how='left')
df_mem_rpas = df_mem_rpas.merge(df_rpas_db, on='codigo_rpas', how='left')
df_mem_rpas.rename(columns = {
    'MEMORANDO PRUEBA DE NOTIFICACIÓN RESOLUCIÓN': 'codigo_final',
    'FECHA MEMORANDO PRUEBA DE NOTIFICACIÓN RESOLUCIÓN': 'fecha_documento'
}, inplace = True)
df_mem_rpas['tipo_documento_id'] = 13
df_mem_rpas['subtipo_documento_id'] = 15
df_mem_rpas['es_manual'] = True
df_mem_rpas['archivado'] = False
df_mem_rpas['documento_origen_id'] = df_mem_rpas['id']
df_mem_rpas.dropna(subset = ['codigo_final'], inplace = True)
df_mem_rpas.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_mem_rpas.drop(columns=['codigo_memo','id_memo','codigo_rpas','id'], inplace = True)

In [946]:
df_mem_rpas.to_sql('documento', con = engine, if_exists='append', index = False)

278

In [947]:
df_ra_imp = df_documentos.iloc[:, np.r_[0,108,109,110]]
df_ra_imp = df_ra_imp.replace(['-', '--', '---','NO','.NO', 'No Aplica'],None)
df_ra_imp = df_ra_imp.merge(df_memos_db, on='codigo_memo', how='left')
df_ra_imp.rename(columns = {
    'APELACIÓN / RESOLUCIÓN': 'codigo_final',
    'FECHA APELACIÓN / RESOLUCIÓN': 'fecha_documento',
    'DECISIÓN RECURSO DE APELACIÓN': 'asunto'
}, inplace = True)
df_ra_imp['tipo_documento_id'] = 10
df_ra_imp['es_manual'] = True
df_ra_imp['archivado'] = False
df_ra_imp['documento_origen_id'] = df_ra_imp['id_memo']
df_ra_imp.dropna(subset = ['codigo_final'], inplace = True)
df_ra_imp.drop_duplicates(subset = ['codigo_final'], inplace = True)
df_ra_imp.drop(columns=['codigo_memo','id_memo'], inplace = True)

df_ra_imp['codigo_final'] = df_ra_imp['codigo_final'].astype(str).str.replace('-\n', '-')
df_ra_imp['codigo_final'] = df_ra_imp['codigo_final'].astype(str).str.strip().str.replace(' / ', '\n')
df_ra_imp['fecha_documento'] = df_ra_imp['fecha_documento'].astype(str).str.strip().str.replace(' / ', '\n')

df_ra_imp['codigo_final'] = df_ra_imp['codigo_final'].astype(str).str.strip().str.split('\n')
df_ra_imp['fecha_documento'] = df_ra_imp['fecha_documento'].astype(str).str.strip().str.split('\n')

df_ra_imp.loc[306, 'fecha_documento'].append('18 de diciembre de 2019')
df_ra_imp.loc[331, 'fecha_documento'].append('21 de febrero de 2020')
df_ra_imp.loc[375, 'fecha_documento'] = ['']
df_ra_imp.loc[464, 'fecha_documento'] = ['']
df_ra_imp.loc[474, 'fecha_documento'] = ['']

df_ra_imp = df_ra_imp.explode(['codigo_final', 'fecha_documento'])

df_ra_imp['fecha_documento'] = df_ra_imp['fecha_documento'].astype(str).str.lower().str.replace(' de ', ' ')

for esp, ing in meses.items():
    df_ra_imp['fecha_documento'] = df_ra_imp['fecha_documento'].astype(str).str.replace(esp, ing)

df_ra_imp['fecha_documento'] = pd.to_datetime(df_ra_imp['fecha_documento'], format='mixed')

In [948]:
df_ra_imp.to_sql('documento', con = engine, if_exists='append', index = False)

70